services:
  accounts:
    image: "haidev257/account:0.0.1-SNAPSHOT"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - haibank
  loans:
    image: "haidev257/loan:0.0.1-SNAPSHOT"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - haibank
  cards:
    image: "haidev257/card:0.0.1-SNAPSHOT"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - haibank
networks:
  haibank:
    driver: "bridge"