server:
  port: 8080

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "HaiDev - Developer"
    email: "haidev@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
